### ISSUE TITLE
[FEATURE] Replace pip Packages with APT/ROS

### ISSUE THREAD

**Issue by benjaminwp18** [CWRUbotix/rov-25#19]
### Is your feature request related to a problem? Please describe

ROS recommends adding apt packages to their repo over using pip packages. We should do that.

### Describe the solution you'd like

Add our packages to the ROS index and use them.

### Related Issues
#20

**Comment by InvincibleRMC** [comment]
@benjaminwp18 Should we follow up with Chris on this?

**Comment by InvincibleRMC** [comment]
Add lgpio package to rosdep

**Comment by InvincibleRMC** [comment]
Add smbus2
